[env]
# Uncomment to set ICED Renderer backend to software renderer tiny-skia.
# ICED_BACKEND = "tiny-skia"
# Using vulkan as it uses less ram compared to opengl or dx11.
#WGPU_BACKEND = "opengl"
#WINIT_UNIX_BACKEND= "x11"
